import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { query } from './pool.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function columnExists(table, column) {
  const { rows } = await query(`
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = $1
      AND column_name = $2
    LIMIT 1
  `, [table, column]);
  return rows.length > 0;
}

async function tableExists(table) {
  const { rows } = await query(`
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = $1
    LIMIT 1
  `, [table]);
  return rows.length > 0;
}

async function renameColumn(table, from, to) {
  if ((await columnExists(table, from)) && !(await columnExists(table, to))) {
    await query(`ALTER TABLE ${table} RENAME COLUMN ${from} TO ${to}`);
  }
}

async function dropColumn(table, column) {
  if (await columnExists(table, column)) {
    await query(`ALTER TABLE ${table} DROP COLUMN ${column}`);
  }
}

async function addColumn(table, column, definition) {
  if (!(await columnExists(table, column))) {
    await query(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
  }
}

async function prepareExistingDatabaseForSchema() {
  if (await tableExists('areas')) {
    await addColumn('areas', 'requires_coordination', 'BOOLEAN NOT NULL DEFAULT false');
  }

  if (await tableExists('areas') && !(await tableExists('coordinations'))) {
    await query(`
      CREATE TABLE IF NOT EXISTS coordinations (
        id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        area_id      INTEGER NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
        name         VARCHAR(200) NOT NULL,
        abbreviation VARCHAR(10)  NOT NULL,
        sort_order   INTEGER NOT NULL DEFAULT 0,
        UNIQUE (area_id, abbreviation)
      )
    `);
  }

  if (await tableExists('documents')) {
    await addColumn('documents', 'coordination_id', 'INTEGER REFERENCES coordinations(id) ON DELETE SET NULL');
  }
  if (await tableExists('users')) {
    await addColumn('users', 'coordination_id', 'INTEGER REFERENCES coordinations(id) ON DELETE SET NULL');
    await addColumn('users', 'profile_picture_url', 'TEXT');
  }
  if (await tableExists('people')) {
    await addColumn('people', 'coordination_id', 'INTEGER REFERENCES coordinations(id) ON DELETE SET NULL');
  }
}

async function refreshAreaCatalog() {
  await query(`
    UPDATE documents
    SET coordination_id = NULL
    WHERE coordination_id IS NOT NULL
      AND coordination_id NOT IN (SELECT id FROM coordinations)
  `);
  await query(`
    UPDATE documents
    SET area_id = 1, coordination_id = NULL
    WHERE area_id IS NULL OR area_id NOT IN (SELECT id FROM areas WHERE id BETWEEN 1 AND 9)
  `);
  await query(`
    UPDATE users
    SET area_id = NULL, coordination_id = NULL
    WHERE area_id IS NOT NULL AND area_id NOT IN (SELECT id FROM areas WHERE id BETWEEN 1 AND 9)
  `);
  await query(`
    UPDATE people
    SET area_id = NULL, coordination_id = NULL
    WHERE area_id IS NOT NULL AND area_id NOT IN (SELECT id FROM areas WHERE id BETWEEN 1 AND 9)
  `);
  await query('DELETE FROM areas WHERE id > 9');

  await query(`
    INSERT INTO areas (id, name, abbreviation, color, lead_name, requires_coordination) VALUES
      (1, 'Coordinacion de Operacion Academica', 'COA', '#29366f', NULL, true),
      (2, 'Coordinacion de Fabrica y Desarrollo', 'CFD', '#43b8bf', NULL, false),
      (3, 'Especializaciones', 'ESP', '#970b12', NULL, false),
      (4, 'Coordinacion B2B', 'B2B', '#c5102e', NULL, false),
      (5, 'Coordinacion de Servicio', 'CSE', '#c51a78', NULL, false),
      (6, 'Coordinacion Pruebas Saber', 'CPS', '#70b52b', NULL, false),
      (7, 'Coordinacion de Proyeccion Social', 'CPSO', '#08743e', NULL, false),
      (8, 'Coordinacion de Desarrollo Profesional', 'CDP', '#9f559b', NULL, false),
      (9, 'Coordinacion General', 'CG', '#f5a000', NULL, false)
    ON CONFLICT (id) DO UPDATE SET
      name = EXCLUDED.name,
      abbreviation = EXCLUDED.abbreviation,
      color = EXCLUDED.color,
      lead_name = EXCLUDED.lead_name,
      requires_coordination = EXCLUDED.requires_coordination
  `);

  await query(`
    INSERT INTO coordinations (id, area_id, name, abbreviation, sort_order) VALUES
      (1, 1, 'Coordinacion Escuela Bellas Artes', 'EBA', 1),
      (2, 1, 'Coordinacion Escuela Transversales', 'ETR', 2),
      (3, 1, 'Coordinacion Escuela Transformacion Empresarial', 'ETE', 3),
      (4, 1, 'Coordinacion Escuela Transformacion de Negocios', 'ETN', 4),
      (5, 1, 'Coordinacion Escuela Transformacion de Ingenierias', 'ETI', 5)
    ON CONFLICT (id) DO UPDATE SET
      area_id = EXCLUDED.area_id,
      name = EXCLUDED.name,
      abbreviation = EXCLUDED.abbreviation,
      sort_order = EXCLUDED.sort_order
  `);

  await query(`SELECT setval(pg_get_serial_sequence('areas', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM areas), 1), true)`);
  await query(`SELECT setval(pg_get_serial_sequence('coordinations', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM coordinations), 1), true)`);
}

export async function migrate() {
  await prepareExistingDatabaseForSchema();

  const schemaPath = path.join(__dirname, '..', '..', 'sql', 'schema.sql');
  const sql = fs.readFileSync(schemaPath, 'utf8');
  await query(sql);

  await renameColumn('areas', 'code', 'abbreviation');
  await renameColumn('document_types', 'short', 'abbreviation');
  await renameColumn('documents', 'code', 'document_number');

  await dropColumn('areas', 'code');
  await dropColumn('document_types', 'short');
  await dropColumn('documents', 'code');
  await dropColumn('document_types', 'key');
  await dropColumn('roles', 'key');
  await dropColumn('people', 'key');
  await dropColumn('users', 'password');
  await dropColumn('users', 'legacy_key');
  await dropColumn('documents', 'legacy_key');
  await dropColumn('workflow_items', 'legacy_key');
  await dropColumn('update_requests', 'legacy_key');

  await addColumn('workflow_items', 'assignee_user_id', 'INTEGER REFERENCES users(id)');
  await addColumn('workflow_items', 'reviewer_user_id', 'INTEGER REFERENCES users(id)');
  await addColumn('workflow_items', 'approver_user_id', 'INTEGER REFERENCES users(id)');
  await addColumn('workflow_items', 'completed_at', 'TIMESTAMPTZ');
  await addColumn('workflow_items', 'completed_by', 'INTEGER REFERENCES users(id)');
  await addColumn('workflow_items', 'reviewed_at', 'TIMESTAMPTZ');
  await addColumn('workflow_items', 'reviewed_by', 'INTEGER REFERENCES users(id)');
  await addColumn('workflow_items', 'decision', 'VARCHAR(30)');
  await addColumn('workflow_items', 'comments', 'TEXT');
  await addColumn('users', 'profile_picture_url', 'TEXT');
  await addColumn('activity_log', 'event_type', "VARCHAR(50) NOT NULL DEFAULT 'general'");
  await addColumn('activity_log', 'details', "JSONB NOT NULL DEFAULT '{}'");
  await addColumn('activity_log', 'created_at', 'TIMESTAMPTZ NOT NULL DEFAULT NOW()');
  await addColumn('documents', 'downloads', 'INTEGER NOT NULL DEFAULT 0');
  await addColumn('documents', 'last_viewed_at', 'TIMESTAMPTZ');
  await addColumn('documents', 'last_downloaded_at', 'TIMESTAMPTZ');
  await addColumn('documents', 'published_at', 'TIMESTAMPTZ');
  await addColumn('documents', 'visible_to_all', 'BOOLEAN NOT NULL DEFAULT false');

  await query(`
    UPDATE documents d
    SET published_at = COALESCE(
      (
        SELECT wi.completed_at
        FROM workflow_items wi
        WHERE wi.doc_id = d.id
          AND wi.decision = 'published'
          AND wi.completed_at IS NOT NULL
        ORDER BY wi.completed_at DESC
        LIMIT 1
      ),
      (
        SELECT al.created_at
        FROM activity_log al
        WHERE al.doc_id = d.id
          AND (
            al.details->>'status' = 'published'
            OR al.details->>'action' = 'publish'
          )
        ORDER BY al.created_at DESC
        LIMIT 1
      ),
      CASE
        WHEN d.state IN ('publicado', 'vencido', 'archivado')
          THEN COALESCE(d.updated::timestamptz, d.created::timestamptz)
        ELSE NULL
      END
    )
    WHERE d.published_at IS NULL
      AND d.state IN ('publicado', 'vencido', 'archivado')
  `);

  await addColumn('areas', 'requires_coordination', 'BOOLEAN NOT NULL DEFAULT false');

  await query(`
    CREATE TABLE IF NOT EXISTS coordinations (
      id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      area_id      INTEGER NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
      name         VARCHAR(200) NOT NULL,
      abbreviation VARCHAR(10)  NOT NULL,
      sort_order   INTEGER NOT NULL DEFAULT 0,
      UNIQUE (area_id, abbreviation)
    )
  `);
  await query('CREATE INDEX IF NOT EXISTS idx_coordinations_area ON coordinations(area_id)');

  await addColumn('documents', 'coordination_id', 'INTEGER REFERENCES coordinations(id) ON DELETE SET NULL');
  await addColumn('users', 'coordination_id', 'INTEGER REFERENCES coordinations(id) ON DELETE SET NULL');
  await addColumn('people', 'coordination_id', 'INTEGER REFERENCES coordinations(id) ON DELETE SET NULL');
  await query('CREATE INDEX IF NOT EXISTS idx_documents_coordination ON documents(coordination_id)');

  await query(`
    WITH interaction_totals AS (
      SELECT
        doc_id,
        COUNT(*) FILTER (WHERE interaction_type = 'view')::int AS views,
        COUNT(*) FILTER (WHERE interaction_type = 'download')::int AS downloads,
        MAX(occurred_at) FILTER (WHERE interaction_type = 'view') AS last_viewed_at,
        MAX(occurred_at) FILTER (WHERE interaction_type = 'download') AS last_downloaded_at
      FROM document_interactions
      GROUP BY doc_id
    )
    UPDATE documents d
    SET views = GREATEST(d.views, totals.views),
        downloads = GREATEST(d.downloads, totals.downloads),
        last_viewed_at = COALESCE(
          GREATEST(d.last_viewed_at, totals.last_viewed_at),
          d.last_viewed_at,
          totals.last_viewed_at
        ),
        last_downloaded_at = COALESCE(
          GREATEST(d.last_downloaded_at, totals.last_downloaded_at),
          d.last_downloaded_at,
          totals.last_downloaded_at
        )
    FROM interaction_totals totals
    WHERE totals.doc_id = d.id
  `);

  await refreshAreaCatalog();

  await query(`
    INSERT INTO document_versions (
      doc_id, version, original_name, stored_name, mime_type, file_size, created_at, created_by, note
    )
    SELECT d.id, d.version, f.original_name, f.stored_name, f.mime_type, f.file_size,
           COALESCE(f.uploaded_at, NOW()), f.uploaded_by, 'Version vigente antes de activar versionamiento'
    FROM documents d
    JOIN document_files f ON f.doc_id = d.id
    ON CONFLICT (doc_id, version) DO NOTHING
  `);

  await query(`
    UPDATE workflow_items wi
    SET assignee_user_id = u.id
    FROM users u
    WHERE wi.assignee_user_id IS NULL
      AND LOWER(wi.assignee) = LOWER(u.name)
  `);

  await query(`
    UPDATE workflow_items
    SET reviewer_user_id = COALESCE(
      reviewer_user_id,
      CASE
        WHEN stage = 'revision' THEN assignee_user_id
        WHEN reviewed_by IS NOT NULL THEN reviewed_by
        ELSE NULL
      END
    )
    WHERE reviewer_user_id IS NULL
  `);

  await query(`
    UPDATE workflow_items wi
    SET reviewer_user_id = (
      SELECT u.id
      FROM users u
      JOIN documents d ON d.id = wi.doc_id
      WHERE u.role_id IN (2, 4, 8)
        AND u.status = 'Activo'
        AND u.area_id = d.area_id
      ORDER BY
        CASE u.role_id
          WHEN 4 THEN 0
          WHEN 2 THEN 1
          ELSE 2
        END,
        u.id
      LIMIT 1
    )
    WHERE wi.completed_at IS NULL
      AND NOT EXISTS (
      SELECT 1
      FROM users current_reviewer
      JOIN documents current_document ON current_document.id = wi.doc_id
      WHERE current_reviewer.id = wi.reviewer_user_id
        AND current_reviewer.role_id IN (2, 4, 8)
        AND current_reviewer.status = 'Activo'
        AND current_reviewer.area_id = current_document.area_id
    )
  `);

  await query(`
    UPDATE workflow_items wi
    SET approver_user_id = (
      SELECT u.id
      FROM users u
      JOIN documents d ON d.id = wi.doc_id
      WHERE u.role_id IN (2, 5, 8)
        AND u.status = 'Activo'
        AND u.area_id = d.area_id
      ORDER BY
        CASE u.role_id
          WHEN 5 THEN 0
          WHEN 2 THEN 1
          ELSE 2
        END,
        u.id
      LIMIT 1
    )
    WHERE wi.completed_at IS NULL
      AND NOT EXISTS (
      SELECT 1
      FROM users current_approver
      JOIN documents current_document ON current_document.id = wi.doc_id
      WHERE current_approver.id = wi.approver_user_id
        AND current_approver.role_id IN (2, 5, 8)
        AND current_approver.status = 'Activo'
        AND current_approver.area_id = current_document.area_id
    )
  `);

  await query(`
    UPDATE workflow_items wi
    SET assignee_user_id = wi.reviewer_user_id,
        assignee = COALESCE(
          (SELECT reviewer.name FROM users reviewer WHERE reviewer.id = wi.reviewer_user_id),
          'Revisor del area pendiente'
        )
    WHERE wi.stage = 'revision'
      AND wi.completed_at IS NULL
  `);

  await query(`
    UPDATE workflow_items wi
    SET assignee_user_id = wi.approver_user_id,
        assignee = COALESCE(
          (SELECT approver.name FROM users approver WHERE approver.id = wi.approver_user_id),
          'Aprobador del area pendiente'
        )
    WHERE wi.stage = 'aprobacion'
      AND wi.completed_at IS NULL
  `);

  await query(`
    UPDATE roles
    SET perms = jsonb_set(perms, '{administrar}', to_jsonb(id = 1), true)
    WHERE NOT (perms ? 'administrar')
  `);
}
