-- Acervo Operaciones - Esquema PostgreSQL
-- Llaves primarias y foraneas internas: siempre INTEGER.

CREATE TABLE IF NOT EXISTS areas (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  VARCHAR(200) NOT NULL,
  abbreviation          VARCHAR(10)  NOT NULL UNIQUE,
  color                 VARCHAR(50),
  lead_name             VARCHAR(200),
  requires_coordination BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS coordinations (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id      INTEGER NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
  name         VARCHAR(200) NOT NULL,
  abbreviation VARCHAR(10)  NOT NULL,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  UNIQUE (area_id, abbreviation)
);

CREATE INDEX IF NOT EXISTS idx_coordinations_area ON coordinations(area_id);

CREATE TABLE IF NOT EXISTS document_types (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(100) NOT NULL,
  abbreviation VARCHAR(10)  NOT NULL,
  icon         VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  description TEXT,
  perms       JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS people (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(200) NOT NULL,
  role_title      VARCHAR(200),
  area_id         INTEGER REFERENCES areas(id),
  coordination_id INTEGER REFERENCES coordinations(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS users (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(200) NOT NULL,
  email           VARCHAR(200) UNIQUE NOT NULL,
  profile_picture_url TEXT,
  role_id         INTEGER NOT NULL REFERENCES roles(id),
  area_id         INTEGER REFERENCES areas(id),
  coordination_id INTEGER REFERENCES coordinations(id) ON DELETE SET NULL,
  status          VARCHAR(20) NOT NULL DEFAULT 'Activo',
  last_access     DATE
);

CREATE TABLE IF NOT EXISTS documents (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id         INTEGER NOT NULL REFERENCES areas(id),
  coordination_id INTEGER REFERENCES coordinations(id) ON DELETE SET NULL,
  type_id         INTEGER NOT NULL REFERENCES document_types(id),
  document_number VARCHAR(50)  NOT NULL,
  name            VARCHAR(500) NOT NULL,
  version         VARCHAR(20)  NOT NULL,
  state           VARCHAR(20)  NOT NULL,
  owner_id        INTEGER NOT NULL REFERENCES people(id),
  vigencia        VARCHAR(20),
  views           INT NOT NULL DEFAULT 0,
  description     TEXT DEFAULT '',
  tags            JSONB NOT NULL DEFAULT '[]',
  related         JSONB NOT NULL DEFAULT '[]',
  ans_ref         VARCHAR(10),
  cargo_ref       VARCHAR(10),
  app_ref         VARCHAR(10),
  created         DATE,
  updated         DATE
);

CREATE INDEX IF NOT EXISTS idx_documents_area ON documents(area_id);
CREATE INDEX IF NOT EXISTS idx_documents_coordination ON documents(coordination_id);
CREATE INDEX IF NOT EXISTS idx_documents_type ON documents(type_id);
CREATE INDEX IF NOT EXISTS idx_documents_state ON documents(state);

CREATE TABLE IF NOT EXISTS document_history (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id         INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  version        VARCHAR(20) NOT NULL,
  history_date   DATE NOT NULL,
  by_person_id   INTEGER REFERENCES people(id),
  note           TEXT
);

CREATE TABLE IF NOT EXISTS workflow_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id     INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  stage      VARCHAR(20) NOT NULL,
  assignee   VARCHAR(200) NOT NULL,
  assignee_user_id INTEGER REFERENCES users(id),
  approver_user_id INTEGER REFERENCES users(id),
  since_date DATE NOT NULL,
  priority   VARCHAR(20) NOT NULL,
  completed_at TIMESTAMPTZ,
  completed_by INTEGER REFERENCES users(id),
  reviewed_at TIMESTAMPTZ,
  reviewed_by INTEGER REFERENCES users(id),
  decision   VARCHAR(30),
  comments   TEXT
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  doc_id  INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, doc_id)
);

CREATE TABLE IF NOT EXISTS document_files (
  doc_id        INTEGER PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
  original_name VARCHAR(500) NOT NULL,
  stored_name   VARCHAR(500) NOT NULL,
  mime_type     VARCHAR(100),
  file_size     BIGINT NOT NULL,
  uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  uploaded_by   INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS document_versions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id        INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  version       VARCHAR(20) NOT NULL,
  original_name VARCHAR(500),
  stored_name   VARCHAR(500),
  mime_type     VARCHAR(100),
  file_size     BIGINT,
  note          TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by    INTEGER REFERENCES users(id),
  UNIQUE (doc_id, version)
);

CREATE INDEX IF NOT EXISTS idx_document_versions_doc ON document_versions(doc_id, created_at DESC);

CREATE TABLE IF NOT EXISTS update_requests (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id     INTEGER NOT NULL REFERENCES documents(id),
  user_id    INTEGER NOT NULL REFERENCES users(id),
  reason     TEXT,
  detail     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activity_log (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  who_user_id    INTEGER REFERENCES users(id),
  who_person_id  INTEGER REFERENCES people(id),
  action         VARCHAR(200) NOT NULL,
  doc_id         INTEGER REFERENCES documents(id),
  when_text      VARCHAR(50),
  event_type     VARCHAR(50) NOT NULL DEFAULT 'general',
  details        JSONB NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notifications (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title        VARCHAR(200) NOT NULL,
  message      TEXT NOT NULL,
  type         VARCHAR(30) NOT NULL DEFAULT 'info',
  doc_id       INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  read_at      TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  email_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  email_error  TEXT,
  emailed_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id) WHERE read_at IS NULL;

-- Catalogos base requeridos para operar la aplicacion.
-- No incluye usuarios ni documentos: esos se crean desde Google Login y el flujo documental.

INSERT INTO areas (id, name, abbreviation, color, lead_name, requires_coordination) VALUES
  (1, 'Coordinacion de Operacion Academica', 'COA', '#2563eb', NULL, true),
  (2, 'Coordinacion de Fabrica y Desarrollo', 'CFD', '#8b5e3c', NULL, false),
  (3, 'Especializaciones', 'ESP', '#ea580c', NULL, false),
  (4, 'Coordinacion B2B', 'B2B', '#991b1b', NULL, false),
  (5, 'Coordinacion de Servicio', 'CSE', '#a78bfa', NULL, false),
  (6, 'Coordinacion Pruebas Saber', 'CPS', '#9333ea', NULL, false),
  (7, 'Coordinacion de Proyeccion Social', 'CPSO', '#78350f', NULL, false),
  (8, 'Coordinacion de Desarrollo Profesional', 'CDP', '#f59e0b', NULL, false)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  abbreviation = EXCLUDED.abbreviation,
  color = EXCLUDED.color,
  lead_name = EXCLUDED.lead_name,
  requires_coordination = EXCLUDED.requires_coordination;

INSERT INTO coordinations (id, area_id, name, abbreviation, sort_order) VALUES
  (1, 1, 'Coordinacion Escuela Bellas Artes', 'EBA', 1),
  (2, 1, 'Coordinacion Escuela Transversales', 'ETR', 2),
  (3, 1, 'Coordinacion Escuela Transformacion Empresarial', 'ETE', 3),
  (4, 1, 'Coordinacion Escuela Transformacion de Negocios', 'ETN', 4),
  (5, 1, 'Coordinacion Escuela Transformacion de Ingenierias', 'ETI', 5)
ON CONFLICT (id) DO UPDATE SET
  area_id = EXCLUDED.area_id,
  name = EXCLUDED.name,
  abbreviation = EXCLUDED.abbreviation,
  sort_order = EXCLUDED.sort_order;

INSERT INTO document_types (id, name, abbreviation, icon) VALUES
  (1, 'Procedimiento', 'PR', 'flow'),
  (2, 'Manual de funciones', 'MF', 'briefcase'),
  (3, 'Descriptor de cargo', 'DC', 'idcard'),
  (4, 'Manual de aplicacion', 'MA', 'app'),
  (5, 'ANS', 'ANS', 'handshake'),
  (6, 'Formato', 'FT', 'form'),
  (7, 'Instructivo', 'IN', 'list'),
  (8, 'Guia', 'GU', 'compass'),
  (9, 'Politica', 'PO', 'shield')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  abbreviation = EXCLUDED.abbreviation,
  icon = EXCLUDED.icon;

INSERT INTO roles (id, name, description, perms) VALUES
  (1, 'Administrador general', 'Control total de la plataforma, configuracion y usuarios.', '{"crear":true,"editar":true,"aprobar":true,"publicar":true,"archivar":true,"consultar":true,"descargar":true,"administrar":true}'::jsonb),
  (2, 'Lider de area', 'Gestiona y aprueba los documentos de su area.', '{"crear":true,"editar":true,"aprobar":true,"publicar":true,"archivar":true,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (3, 'Editor documental', 'Crea y edita documentos; los envia a revision.', '{"crear":true,"editar":true,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (4, 'Revisor', 'Revisa documentos y devuelve observaciones.', '{"crear":false,"editar":false,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (5, 'Aprobador', 'Aprueba documentos revisados para su publicacion.', '{"crear":false,"editar":false,"aprobar":true,"publicar":true,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (6, 'Usuario consultor', 'Consulta y descarga documentos publicados.', '{"crear":false,"editar":false,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (7, 'Auditor / lector institucional', 'Lectura y trazabilidad sin descarga.', '{"crear":false,"editar":false,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":false,"administrar":false}'::jsonb),
  (8, 'Coordinador Operacion Academica', 'Gestiona, revisa, aprueba y publica documentos de Operacion Academica y sus subcoordinaciones.', '{"crear":true,"editar":true,"aprobar":true,"publicar":true,"archivar":true,"consultar":true,"descargar":true,"administrar":false}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  perms = EXCLUDED.perms;

SELECT setval(pg_get_serial_sequence('areas', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM areas), 1), true);
SELECT setval(pg_get_serial_sequence('coordinations', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM coordinations), 1), true);
SELECT setval(pg_get_serial_sequence('document_types', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM document_types), 1), true);
SELECT setval(pg_get_serial_sequence('roles', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM roles), 1), true);
SELECT setval(pg_get_serial_sequence('people', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM people), 1), true);
