-- Acervo Operaciones - Esquema PostgreSQL
-- Llaves primarias y foraneas internas: siempre INTEGER.

CREATE TABLE IF NOT EXISTS areas (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(200) NOT NULL,
  abbreviation VARCHAR(10)  NOT NULL UNIQUE,
  color        VARCHAR(50),
  lead_name    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS document_types (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(100) NOT NULL,
  abbreviation VARCHAR(10)  NOT NULL,
  icon         VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  description TEXT,
  perms       JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS people (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(200) NOT NULL,
  role_title VARCHAR(200),
  area_id    INTEGER REFERENCES areas(id)
);

CREATE TABLE IF NOT EXISTS users (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(200) NOT NULL,
  email       VARCHAR(200) UNIQUE NOT NULL,
  role_id     INTEGER NOT NULL REFERENCES roles(id),
  area_id     INTEGER REFERENCES areas(id),
  status      VARCHAR(20) NOT NULL DEFAULT 'Activo',
  last_access DATE
);

CREATE TABLE IF NOT EXISTS documents (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id         INTEGER NOT NULL REFERENCES areas(id),
  type_id         INTEGER NOT NULL REFERENCES document_types(id),
  document_number VARCHAR(50)  NOT NULL,
  name            VARCHAR(500) NOT NULL,
  version         VARCHAR(20)  NOT NULL,
  state           VARCHAR(20)  NOT NULL,
  owner_id        INTEGER NOT NULL REFERENCES people(id),
  vigencia        VARCHAR(20),
  views           INT NOT NULL DEFAULT 0,
  description     TEXT DEFAULT '',
  tags            JSONB NOT NULL DEFAULT '[]',
  related         JSONB NOT NULL DEFAULT '[]',
  ans_ref         VARCHAR(10),
  cargo_ref       VARCHAR(10),
  app_ref         VARCHAR(10),
  created         DATE,
  updated         DATE
);

CREATE INDEX IF NOT EXISTS idx_documents_area ON documents(area_id);
CREATE INDEX IF NOT EXISTS idx_documents_type ON documents(type_id);
CREATE INDEX IF NOT EXISTS idx_documents_state ON documents(state);

CREATE TABLE IF NOT EXISTS document_history (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id         INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  version        VARCHAR(20) NOT NULL,
  history_date   DATE NOT NULL,
  by_person_id   INTEGER REFERENCES people(id),
  note           TEXT
);

CREATE TABLE IF NOT EXISTS workflow_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id     INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  stage      VARCHAR(20) NOT NULL,
  assignee   VARCHAR(200) NOT NULL,
  assignee_user_id INTEGER REFERENCES users(id),
  approver_user_id INTEGER REFERENCES users(id),
  since_date DATE NOT NULL,
  priority   VARCHAR(20) NOT NULL,
  completed_at TIMESTAMPTZ,
  completed_by INTEGER REFERENCES users(id),
  reviewed_at TIMESTAMPTZ,
  reviewed_by INTEGER REFERENCES users(id),
  decision   VARCHAR(30),
  comments   TEXT
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  doc_id  INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, doc_id)
);

CREATE TABLE IF NOT EXISTS document_files (
  doc_id        INTEGER PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
  original_name VARCHAR(500) NOT NULL,
  stored_name   VARCHAR(500) NOT NULL,
  mime_type     VARCHAR(100),
  file_size     BIGINT NOT NULL,
  uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  uploaded_by   INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS document_versions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id        INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  version       VARCHAR(20) NOT NULL,
  original_name VARCHAR(500),
  stored_name   VARCHAR(500),
  mime_type     VARCHAR(100),
  file_size     BIGINT,
  note          TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by    INTEGER REFERENCES users(id),
  UNIQUE (doc_id, version)
);

CREATE INDEX IF NOT EXISTS idx_document_versions_doc ON document_versions(doc_id, created_at DESC);

CREATE TABLE IF NOT EXISTS update_requests (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id     INTEGER NOT NULL REFERENCES documents(id),
  user_id    INTEGER NOT NULL REFERENCES users(id),
  reason     TEXT,
  detail     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activity_log (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  who_user_id    INTEGER REFERENCES users(id),
  who_person_id  INTEGER REFERENCES people(id),
  action         VARCHAR(200) NOT NULL,
  doc_id         INTEGER REFERENCES documents(id),
  when_text      VARCHAR(50),
  event_type     VARCHAR(50) NOT NULL DEFAULT 'general',
  details        JSONB NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notifications (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title        VARCHAR(200) NOT NULL,
  message      TEXT NOT NULL,
  type         VARCHAR(30) NOT NULL DEFAULT 'info',
  doc_id       INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  read_at      TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  email_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  email_error  TEXT,
  emailed_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id) WHERE read_at IS NULL;

-- Catalogos base requeridos para operar la aplicacion.
-- No incluye usuarios ni documentos: esos se crean desde Google Login y el flujo documental.

INSERT INTO areas (id, name, abbreviation, color, lead_name) VALUES
  (1, 'Fabrica de Contenidos', 'FCO', 'var(--area-fco)', 'Laura Restrepo Mejia'),
  (2, 'Practicas', 'PRA', 'var(--area-pra)', 'Mauricio Salazar Rios'),
  (3, 'Homologaciones', 'HOM', 'var(--area-hom)', 'Diana Marcela Ruiz'),
  (4, 'Operacion Academica de Pregrado', 'OAP', 'var(--area-oap)', 'Carlos Andres Gomez'),
  (5, 'Operacion Academica de Posgrado', 'OPG', 'var(--area-opg)', 'Andrea Forero Castro'),
  (6, 'Pruebas Saber', 'PSB', 'var(--area-psb)', 'Julian Ospina Velez')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  abbreviation = EXCLUDED.abbreviation,
  color = EXCLUDED.color,
  lead_name = EXCLUDED.lead_name;

INSERT INTO document_types (id, name, abbreviation, icon) VALUES
  (1, 'Procedimiento', 'PR', 'flow'),
  (2, 'Manual de funciones', 'MF', 'briefcase'),
  (3, 'Descriptor de cargo', 'DC', 'idcard'),
  (4, 'Manual de aplicacion', 'MA', 'app'),
  (5, 'ANS', 'ANS', 'handshake'),
  (6, 'Formato', 'FT', 'form'),
  (7, 'Instructivo', 'IN', 'list'),
  (8, 'Guia', 'GU', 'compass'),
  (9, 'Politica', 'PO', 'shield')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  abbreviation = EXCLUDED.abbreviation,
  icon = EXCLUDED.icon;

INSERT INTO roles (id, name, description, perms) VALUES
  (1, 'Administrador general', 'Control total de la plataforma, configuracion y usuarios.', '{"crear":true,"editar":true,"aprobar":true,"publicar":true,"archivar":true,"consultar":true,"descargar":true,"administrar":true}'::jsonb),
  (2, 'Lider de area', 'Gestiona y aprueba los documentos de su area.', '{"crear":true,"editar":true,"aprobar":true,"publicar":true,"archivar":true,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (3, 'Editor documental', 'Crea y edita documentos; los envia a revision.', '{"crear":true,"editar":true,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (4, 'Revisor', 'Revisa documentos y devuelve observaciones.', '{"crear":false,"editar":false,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (5, 'Aprobador', 'Aprueba documentos revisados para su publicacion.', '{"crear":false,"editar":false,"aprobar":true,"publicar":true,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (6, 'Usuario consultor', 'Consulta y descarga documentos publicados.', '{"crear":false,"editar":false,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":true,"administrar":false}'::jsonb),
  (7, 'Auditor / lector institucional', 'Lectura y trazabilidad sin descarga.', '{"crear":false,"editar":false,"aprobar":false,"publicar":false,"archivar":false,"consultar":true,"descargar":false,"administrar":false}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  perms = EXCLUDED.perms;

INSERT INTO people (id, name, role_title, area_id) VALUES
  (1, 'Laura Restrepo Mejia', 'Lider de Fabrica de Contenidos', 1),
  (2, 'Felipe Arango Mesa', 'Editor documental', 1),
  (3, 'Mauricio Salazar Rios', 'Lider de Practicas', 2),
  (4, 'Valentina Rios Tamayo', 'Analista de Practicas', 2),
  (5, 'Diana Marcela Ruiz', 'Lider de Homologaciones', 3),
  (6, 'Sebastian Cardenas', 'Analista de Homologaciones', 3),
  (7, 'Carlos Andres Gomez', 'Lider de Pregrado', 4),
  (8, 'Andrea Forero Castro', 'Lider de Posgrado', 5),
  (9, 'Julian Ospina Velez', 'Lider de Pruebas Saber', 6)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  role_title = EXCLUDED.role_title,
  area_id = EXCLUDED.area_id;

SELECT setval(pg_get_serial_sequence('areas', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM areas), 1), true);
SELECT setval(pg_get_serial_sequence('document_types', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM document_types), 1), true);
SELECT setval(pg_get_serial_sequence('roles', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM roles), 1), true);
SELECT setval(pg_get_serial_sequence('people', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM people), 1), true);
