-- Acervo Operaciones - Esquema PostgreSQL
-- Llaves primarias y foraneas internas: siempre INTEGER.

CREATE TABLE IF NOT EXISTS areas (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(200) NOT NULL,
  abbreviation VARCHAR(10)  NOT NULL UNIQUE,
  color        VARCHAR(50),
  lead_name    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS document_types (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(100) NOT NULL,
  abbreviation VARCHAR(10)  NOT NULL,
  icon         VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  description TEXT,
  perms       JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS people (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(200) NOT NULL,
  role_title VARCHAR(200),
  area_id    INTEGER REFERENCES areas(id)
);

CREATE TABLE IF NOT EXISTS users (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(200) NOT NULL,
  email       VARCHAR(200) UNIQUE NOT NULL,
  password    VARCHAR(200) NOT NULL,
  role_id     INTEGER NOT NULL REFERENCES roles(id),
  area_id     INTEGER REFERENCES areas(id),
  status      VARCHAR(20) NOT NULL DEFAULT 'Activo',
  last_access DATE
);

CREATE TABLE IF NOT EXISTS documents (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id         INTEGER NOT NULL REFERENCES areas(id),
  type_id         INTEGER NOT NULL REFERENCES document_types(id),
  document_number VARCHAR(50)  NOT NULL,
  name            VARCHAR(500) NOT NULL,
  version         VARCHAR(20)  NOT NULL,
  state           VARCHAR(20)  NOT NULL,
  owner_id        INTEGER NOT NULL REFERENCES people(id),
  vigencia        VARCHAR(20),
  views           INT NOT NULL DEFAULT 0,
  description     TEXT DEFAULT '',
  tags            JSONB NOT NULL DEFAULT '[]',
  related         JSONB NOT NULL DEFAULT '[]',
  ans_ref         VARCHAR(10),
  cargo_ref       VARCHAR(10),
  app_ref         VARCHAR(10),
  created         DATE,
  updated         DATE
);

CREATE INDEX IF NOT EXISTS idx_documents_area ON documents(area_id);
CREATE INDEX IF NOT EXISTS idx_documents_type ON documents(type_id);
CREATE INDEX IF NOT EXISTS idx_documents_state ON documents(state);

CREATE TABLE IF NOT EXISTS document_history (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id         INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  version        VARCHAR(20) NOT NULL,
  history_date   DATE NOT NULL,
  by_person_id   INTEGER REFERENCES people(id),
  note           TEXT
);

CREATE TABLE IF NOT EXISTS workflow_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id     INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  stage      VARCHAR(20) NOT NULL,
  assignee   VARCHAR(200) NOT NULL,
  since_date DATE NOT NULL,
  priority   VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  doc_id  INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, doc_id)
);

CREATE TABLE IF NOT EXISTS document_files (
  doc_id        INTEGER PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
  original_name VARCHAR(500) NOT NULL,
  stored_name   VARCHAR(500) NOT NULL,
  mime_type     VARCHAR(100),
  file_size     BIGINT NOT NULL,
  uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  uploaded_by   INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS update_requests (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id     INTEGER NOT NULL REFERENCES documents(id),
  user_id    INTEGER NOT NULL REFERENCES users(id),
  reason     TEXT,
  detail     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activity_log (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  who_user_id    INTEGER REFERENCES users(id),
  who_person_id  INTEGER REFERENCES people(id),
  action         VARCHAR(200) NOT NULL,
  doc_id         INTEGER REFERENCES documents(id),
  when_text      VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS notifications (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title        VARCHAR(200) NOT NULL,
  message      TEXT NOT NULL,
  type         VARCHAR(30) NOT NULL DEFAULT 'info',
  doc_id       INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  read_at      TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  email_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  email_error  TEXT,
  emailed_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id) WHERE read_at IS NULL;
