-- ============================================================================
-- ACERVO DOCUMENTAL
-- Migración: métricas de uso y analítica documental
-- Identificador: 20260804_001_document_usage_analytics
-- Fecha: 2026-08-04
--
-- Objetivo:
--   1. Conservar descargas y fechas de última interacción por documento.
--   2. Registrar el histórico detallado de visualizaciones y descargas.
--   3. Crear índices para rankings, tendencias y consultas por usuario.
--   4. Reconciliar los acumulados con los eventos que ya existan.
--
-- Características:
--   - Compatible con PostgreSQL.
--   - Idempotente: puede ejecutarse más de una vez de forma segura.
--   - No elimina ni sobrescribe información histórica.
--
-- Importante:
--   El detalle histórico solo existe para eventos registrados después de que
--   esta funcionalidad entre en operación. El contador previo de views se
--   conserva y no se transforma en eventos ficticios.
-- ============================================================================

BEGIN;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS downloads INTEGER NOT NULL DEFAULT 0;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS last_viewed_at TIMESTAMPTZ;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS last_downloaded_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS document_interactions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id           INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  user_id          INTEGER REFERENCES users(id) ON DELETE SET NULL,
  interaction_type VARCHAR(20) NOT NULL
    CHECK (interaction_type IN ('view', 'download')),
  document_version VARCHAR(20),
  source           VARCHAR(40) NOT NULL DEFAULT 'application',
  metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_document_interactions_doc_type_date
  ON document_interactions(doc_id, interaction_type, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_document_interactions_type_date
  ON document_interactions(interaction_type, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_document_interactions_user_date
  ON document_interactions(user_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_document_interactions_date
  ON document_interactions(occurred_at DESC);

COMMENT ON TABLE document_interactions IS
  'Histórico detallado de visualizaciones y descargas de documentos del Acervo.';

COMMENT ON COLUMN document_interactions.interaction_type IS
  'Tipo de interacción: view para consulta o download para descarga.';

COMMENT ON COLUMN document_interactions.document_version IS
  'Versión del documento que estaba vigente o fue descargada al registrar el evento.';

COMMENT ON COLUMN document_interactions.source IS
  'Punto funcional que originó el evento, por ejemplo document_detail, current_file o version_file.';

COMMENT ON COLUMN document_interactions.metadata IS
  'Información técnica adicional del evento sin reemplazar sus campos estructurados.';

COMMENT ON COLUMN documents.downloads IS
  'Total histórico acumulado de descargas del documento.';

COMMENT ON COLUMN documents.last_viewed_at IS
  'Fecha y hora de la última visualización registrada.';

COMMENT ON COLUMN documents.last_downloaded_at IS
  'Fecha y hora de la última descarga registrada.';

-- Si ya existen eventos, garantiza que los acumulados nunca queden por debajo
-- del histórico registrado. GREATEST conserva contadores anteriores superiores.
WITH interaction_totals AS (
  SELECT
    doc_id,
    COUNT(*) FILTER (WHERE interaction_type = 'view')::int AS views,
    COUNT(*) FILTER (WHERE interaction_type = 'download')::int AS downloads,
    MAX(occurred_at) FILTER (WHERE interaction_type = 'view') AS last_viewed_at,
    MAX(occurred_at) FILTER (WHERE interaction_type = 'download') AS last_downloaded_at
  FROM document_interactions
  GROUP BY doc_id
)
UPDATE documents AS document
SET
  views = GREATEST(document.views, totals.views),
  downloads = GREATEST(document.downloads, totals.downloads),
  last_viewed_at = COALESCE(
    GREATEST(document.last_viewed_at, totals.last_viewed_at),
    document.last_viewed_at,
    totals.last_viewed_at
  ),
  last_downloaded_at = COALESCE(
    GREATEST(document.last_downloaded_at, totals.last_downloaded_at),
    document.last_downloaded_at,
    totals.last_downloaded_at
  )
FROM interaction_totals AS totals
WHERE totals.doc_id = document.id;

COMMIT;

-- No se incluye rollback automático porque eliminar estas columnas o la tabla
-- destruiría datos históricos. Cualquier reversión debe preservar primero la
-- información de document_interactions y contar con aprobación explícita.
